name: Continous Deployment

env:
  IMAGE_NAME: "discord_bosklapper_bot"

on:
  push:
    branches:
      - master
      
jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout Main branch
        uses: actions/checkout@v2
      - name: Build Docker image        
        env:          
          GITHUB_SHA: ${{ github.sha }}        
        run: docker build -t $(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .  
      - name: Stop container
        env:          
          GITHUB_SHA: ${{ github.sha }}        
        run: docker stop $(echo $IMAGE_NAME) || true
      - name: Delete old container
        env:          
          GITHUB_SHA: ${{ github.sha }}        
        run: docker rm $(echo $IMAGE_NAME) || true
      - name: Start new container
        env:          
          GITHUB_SHA: ${{ github.sha }}        
        run: docker run -d --restart always -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN  }} -e GH_TOKEN=${{ secrets.GH_TOKEN  }} -v calendar:/saved --name $(echo $IMAGE_NAME) $(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
      - name: Remove old images
        env:          
          GITHUB_SHA: ${{ github.sha }}        
        run: docker image prune -f -a
      - name: Prune system
        run: docker system prune

